# Generated by Django 4.1.7 on 2023-03-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_alter_item_category_alter_item_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computer",
            name="category",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="name",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="price",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="printer",
            name="category",
        ),
        migrations.RemoveField(
            model_name="printer",
            name="name",
        ),
        migrations.RemoveField(
            model_name="printer",
            name="price",
        ),
        migrations.RemoveField(
            model_name="printer",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="scanner",
            name="category",
        ),
        migrations.RemoveField(
            model_name="scanner",
            name="name",
        ),
        migrations.RemoveField(
            model_name="scanner",
            name="price",
        ),
        migrations.RemoveField(
            model_name="scanner",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="computermodel",
            name="memory",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="computermodel",
            name="processor",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="computermodel",
            name="storage",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="printermodel",
            name="print_color",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="printermodel",
            name="print_technology",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="scannermodel",
            name="scan_resolution",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="scannermodel",
            name="scan_technology",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
