# Generated by Django 4.1.7 on 2023-03-26 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_manufacturer_remove_computermodel_manufacturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="computermodel",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.manufacturer",
            ),
        ),
    ]
