# Generated by Django 4.1.7 on 2023-03-28 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_alter_computerassignment_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computerassignment",
            name="computer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="computer_assignments",
                to="inventory.computer",
            ),
        ),
    ]
