# Generated by Django 4.1.7 on 2023-03-29 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_alter_computerassignment_computer"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="ext",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="computerassignment",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="computer_assignments",
                to="inventory.employee",
            ),
        ),
    ]
