# Generated by Django 4.1.7 on 2023-04-05 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_alter_employee_options_receiveitem_giveitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="computerassignment",
            name="date_assigned",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="dept",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.department",
                verbose_name="department",
            ),
        ),
    ]
