# Generated by Django 4.1.7 on 2023-04-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0017_alter_printermodel_manufacturer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printermodel",
            name="print_color",
            field=models.BooleanField(default=True),
        ),
    ]
