# Generated by Django 4.1.7 on 2023-04-07 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0019_printtechnology_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printermodel",
            name="print_technology",
        ),
    ]
