# Generated by Django 4.1.7 on 2023-04-07 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0020_remove_printermodel_print_technology"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PrintTechnology",
        ),
    ]
