# Generated by Django 4.1.7 on 2023-04-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0021_delete_printtechnology"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="address1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
